<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Documento extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Documentos_model');
    } 

    /*
     * Listing of documentos
     */
    function index()
    {
        $data['documentos'] = $this->Documentos_model->get_all_documentos();
        
        $data['_view'] = 'documentos/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new documento
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('titulo','Titulo','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'titulo' => $this->input->post('titulo'),
				'orden' => $this->input->post('orden'),
            );
            
            $documento_id = $this->Documentos_model->add_documento($params);
            redirect('documento/index');
        }
        else
        {            
            $data['_view'] = 'documentos/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a documento
     */
    function edit($documento_id)
    {   
        // check if the documento exists before trying to edit it
        $data['documento'] = $this->Documentos_model->get_documento($documento_id);
        
        if(isset($data['documento']['documento_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('titulo','Titulo','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'titulo' => $this->input->post('titulo'),
					'orden' => $this->input->post('orden'),
                );

                $this->Documentos_model->update_documento($documento_id,$params);            
                redirect('documento/index');
            }
            else
            {
                $data['_view'] = 'documentos/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The documento you are trying to edit does not exist.');
    } 

    /*
     * Deleting documento
     */
    function remove($documento_id)
    {
        $documento = $this->Documentos_model->get_documento($documento_id);

        // check if the documento exists before trying to delete it
        if(isset($documento['documento_id']))
        {
            $this->Documentos_model->delete_documento($documento_id);
            redirect('documento/index');
        }
        else
            show_error('The documento you are trying to delete does not exist.');
    }


    function ver($documento_id=""){
        $data["documento"]= $this->Documentos_model->get_documento($documento_id);
        $data['documentos'] = $this->Documentos_model->get_all_documentos();

        if(isset($data["documento"]['documento_id'])){
            
            $ruta=FCPATH."docs/".$data["documento"]['documento_id'].".txt";
            if(file_exists($ruta)){
                $data["documento"]["contenido"]=file_get_contents($ruta);
            }else{
                $data["documento"]["contenido"]= "No Existe el doc";
            }
            
            $data['_view'] = 'documentos/ver';
            $this->load->view('layouts/main',$data);

        }else{
            echo "NO EXISTE";
        }
    }
    
}
