<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Documentos_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get documento by documento_id
     */
    function get_documento($documento_id)
    {
        return $this->db->get_where('documentos',array('documento_id'=>$documento_id))->row_array();
    }
        
    /*
     * Get all documentos
     */
    function get_all_documentos()
    {
        $this->db->order_by('orden', 'asc');
        return $this->db->get('documentos')->result_array();
    }
        
    /*
     * function to add new documento
     */
    function add_documento($params)
    {
        $this->db->insert('documentos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update documento
     */
    function update_documento($documento_id,$params)
    {
        $this->db->where('documento_id',$documento_id);
        return $this->db->update('documentos',$params);
    }
    
    /*
     * function to delete documento
     */
    function delete_documento($documento_id)
    {
        return $this->db->delete('documentos',array('documento_id'=>$documento_id));
    }
}
